servo_node:
  ros__parameters:
    moveit_servo:
      ros__parameters:
        move_group: arm
        ee_frame_name: ee_link
        kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
        kinematics_solver_search_resolution: 0.005
        kinematics_solver_timeout: 0.05
