servo_node:                      
  ros__parameters:
    moveit_servo:
      ros__parameters:
        # MoveGroup definido en tu SRDF
        move_group: arm

        # Marco del efector final
        ee_frame_name: ee_link

        # CINEMÁTICA
        kinematics_solver:                   kdl_kinematics_plugin/KDLKinematicsPlugin
        kinematics_solver_search_resolution: 0.005
        kinematics_solver_timeout:           0.05

        # VELOCIDADES LINEALES (m/s)
        min_linear_speed: 0.01
        max_linear_speed: 0.15

        # VELOCIDADES ANGULARES (rad/s)
        min_angular_speed: 0.1
        max_angular_speed: 1.0

        # PUBLICACIÓN & COLISIONES
        collision_check: true
        publish_period:    0.01

        # ESCALAS DE COMANDO
        scale_linear:  1.0
        scale_angular: 1.0
